version: "3.9"
services:
  mariadb:
    container_name: mmss_mariadb
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lcyzuishuai
      MYSQL_DATABASE: 'MMSS'
    networks:
      - mmss
    expose:
      - 3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d

  redis:
    container_name: mmss_redis
    image: redis
    restart: always
    networks:
      - mmss
    expose:
      - 6379
    volumes:
      - ./data:/data

  backend:
    container_name: mmss
    build: .
    environment:
      DSN: root:lcyzuishuai@tcp(mmss_mariadb:3306)/MMSS?charset=utf8mb4&parseTime=True&loc=Local
      Redis_Host: mmss_redis
    networks:
      - mmss
    ports:
    - 58888:58888
    links:
      - mariadb
      - redis

networks:
  mmss:
